- type: entity # Floofstation
  name: pomegranate
  parent: FoodProduceBase
  id: FoodPomegranate
  description: A delicious, sweet fruit, believed to have special properties.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
    - spooky
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 40
        reagents:
        - ReagentId: Pomelustine
          Quantity: 30
        - ReagentId: Nutriment
          Quantity: 10
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/pomegranate.rsi
  - type: Produce
    seedId: pomegranate
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePomegranate
        Quantity: 20
  - type: SliceableFood
    count: 2
    slice: FoodPomegranateSlice
  - type: Tag
    tags:
    - Fruit

- type: entity # Floofstation
  name: pomegranate slice
  parent: ProduceSliceBase
  id: FoodPomegranateSlice
  description: A delicious, sweet fruit, believed to have special properties.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
    - spooky
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/pomegranate.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Pomelustine
          Quantity: 15
        - ReagentId: Nutriment
          Quantity: 5
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePomegranate
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
    - Slice
